# Generated by Django 4.2.7 on 2023-12-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_attachment_attachment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
